### ISSUE TITLE
Z not working

### ISSUE THREAD

**Issue by nobaj** [bigtreetech/BIGTREETECH-SKR-MINI-V1.1#35]
I don't know why my z motor is not moving, if I connect the motor to another axis, it works.
. 
I also replaced the driver (they are both new drivers) but this does nothing. 

Also I move the steps down to 80 to see if it was something to do with the steps per mm. Still nothing. 

I tried both connectors, (I know they are in parallel with the same driver) 

I used the same cable to connect the motor to another axis and it worked, (same cable, same motor different axis) 

Is there a conf or something I need to change on marlin ? 
-----------------------------------------------------------------------------------------------------------------------------------------

UPDATE:

If I connect 2 motors (one in each port) it works..... But my printer only have 1 z motor, is there are marlin option to use only one? a jumper on board??? something??? 

UPDATE 2:

There is a picture with some jumpers in one of the z sockets.... It worked... I am so dumb.

**Comment by nobaj** [comment]
I want to rule out everything before saying it is a faulty motherboard

**Comment by Rodov** [comment]
This problem was mentioned before and has been successfully solved:
#9 (How to connect a single Z motor?)
Please close the issue, if everything work fine.
