### ISSUE TITLE
Marlin 2.0 with BLTouch Compiling issue

### ISSUE THREAD

**Issue by anm8tor** [bigtreetech/BIGTREETECH-SKR-MINI-V1.1#5]
So I was in the process of changing some settings to the Marlin 2.0 build provided here and ran into several compiling errors. I'm not sure I am posting the correct data for someone to help, but this is my first time ever posting. So here goes; I also included a screenshot of the "problems" portion from PIO:

In file included from Marlin\src\HAL\HAL_STM32F1\../../inc/MarlinConfig.h:41,
from Marlin\src\HAL\HAL_STM32F1\HAL_Servo_STM32F1.cpp:26:
Marlin\src\HAL\HAL_STM32F1\../../inc/SanityCheck.h:957:8: error: #error "SERVO0_PIN must be defined for your servo or BLTOUCH probe."
#error "SERVO0_PIN must be defined for your servo or BLTOUCH probe."
^~~~~
Marlin\src\HAL\HAL_STM32F1\../../inc/SanityCheck.h:1777:4: error: #error "TMC2208 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
#error "TMC2208 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
^~~~~
Marlin\src\HAL\HAL_STM32F1\../../inc/SanityCheck.h:1841:4: error: #error "TMC2208 Software Serial is supported only on AVR and LPC1768 platforms."
#error "TMC2208 Software Serial is supported only on AVR and LPC1768 platforms."
^~~~~
In file included from Marlin\src\HAL\shared\../../inc/MarlinConfigPre.h:36,
from Marlin\src\HAL\shared\../../inc/MarlinConfig.h:28,
from Marlin\src\HAL\shared\I2cEeprom.cpp:28:
Marlin\src\HAL\shared\../../inc/Conditionals_LCD.h:51: warning: "ENCODER_PULSES_PER_STEP" redefined
#define ENCODER_PULSES_PER_STEP 1

In file included from Marlin\src\HAL\shared\../../inc/MarlinConfigPre.h:35,
from Marlin\src\HAL\shared\../../inc/MarlinConfig.h:28,
from Marlin\src\HAL\shared\I2cEeprom.cpp:28:
Marlin\src\HAL\shared\../../inc/../../Configuration.h:1547: note: this is the location of the previous definition
#define ENCODER_PULSES_PER_STEP 2

In file included from Marlin\src\HAL\shared\../../inc/MarlinConfigPre.h:36,
from Marlin\src\HAL\shared\../../inc/MarlinConfig.h:28,Compiling .pioenvs\BIGTREE_SKR_MINI\src\src\HAL\shared\servo.cpp.o

from Marlin\src\HAL\shared\I2cEeprom.cpp:28:
Marlin\src\HAL\shared\../../inc/Conditionals_LCD.h:52: warning: "ENCODER_STEPS_PER_MENU_ITEM" redefined
#define ENCODER_STEPS_PER_MENU_ITEM 1

In file included from Marlin\src\HAL\shared\../../inc/MarlinConfigPre.h:35,
from Marlin\src\HAL\shared\../../inc/MarlinConfig.h:28,
from Marlin\src\HAL\shared\I2cEeprom.cpp:28:
Marlin\src\HAL\shared\../../inc/../../Configuration.h:1553: note: this is the location of the previous definition
#define ENCODER_STEPS_PER_MENU_ITEM 2

In file included from Marlin\src\HAL\shared\../../inc/MarlinConfigPre.h:36,
from Marlin\src\HAL\shared\../../inc/MarlinConfig.h:28,
from Marlin\src\HAL\shared\SpiEeprom.cpp:28:
Marlin\src\HAL\shared\../../inc/Conditionals_LCD.h:51: warning: "ENCODER_PULSES_PER_STEP" redefined
#define ENCODER_PULSES_PER_STEP 1

In file included from Marlin\src\HAL\shared\../../inc/MarlinConfigPre.h:35,
from Marlin\src\HAL\shared\../../inc/MarlinConfig.h:28,
from Marlin\src\HAL\shared\SpiEeprom.cpp:28:
Marlin\src\HAL\shared\../../inc/../../Configuration.h:1547: note: this is the location of the previous definition
#define ENCODER_PULSES_PER_STEP 2

In file included from Marlin\src\HAL\shared\../../inc/MarlinConfigPre.h:36,
from Marlin\src\HAL\shared\../../inc/MarlinConfig.h:28,
from Marlin\src\HAL\shared\SpiEeprom.cpp:28:
Marlin\src\HAL\shared\../../inc/Conditionals_LCD.h:52: warning: "ENCODER_STEPS_PER_MENU_ITEM" redefined
#define ENCODER_STEPS_PER_MENU_ITEM 1

In file included from Marlin\src\HAL\shared\../../inc/MarlinConfigPre.h:35,
from Marlin\src\HAL\shared\../../inc/MarlinConfig.h:28,
from Marlin\src\HAL\shared\SpiEeprom.cpp:28:
Marlin\src\HAL\shared\../../inc/../../Configuration.h:1553: note: this is the location of the previous definition
#define ENCODER_STEPS_PER_MENU_ITEM 2

In file included from Marlin\src\HAL\HAL_STM32F1\../../inc/MarlinConfig.h:41,
from Marlin\src\HAL\HAL_STM32F1\persistent_store_flash.cpp:32:
Marlin\src\HAL\HAL_STM32F1\../../inc/SanityCheck.h:957:8: error: #error "SERVO0_PIN must be defined for your servo or BLTOUCH probe."
#error "SERVO0_PIN must be defined for your servo or BLTOUCH probe."
^~~~~
Marlin\src\HAL\HAL_STM32F1\../../inc/SanityCheck.h:1777:4: error: #error "TMC2208 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
#error "TMC2208 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
^~~~~
Marlin\src\HAL\HAL_STM32F1\../../inc/SanityCheck.h:1841:4: error: #error "TMC2208 Software Serial is supported only on AVR and LPC1768 platforms."
#error "TMC2208 Software Serial is supported only on AVR and LPC1768 platforms."
^~~~~
In file included from Marlin\src\HAL\HAL_STM32F1\../../inc/MarlinConfig.h:41,
from Marlin\src\HAL\HAL_STM32F1\persistent_store_sdcard.cpp:30:
Marlin\src\HAL\HAL_STM32F1\../../inc/SanityCheck.h:957:8: error: #error "SERVO0_PIN must be defined for your servo or BLTOUCH probe."
#error "SERVO0_PIN must be defined for your servo or BLTOUCH probe."
^~~~~
Marlin\src\HAL\HAL_STM32F1\../../inc/SanityCheck.h:1777:4: error: #error "TMC2208 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
#error "TMC2208 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
^~~~~
Marlin\src\HAL\HAL_STM32F1\../../inc/SanityCheck.h:1841:4: error: #error "TMC2208 Software Serial is supported only on AVR and LPC1768 platforms."
#error "TMC2208 Software Serial is supported only on AVR and LPC1768 platforms."
^~~~~
In file included from Marlin\src\HAL\HAL_STM32F1\../../inc/MarlinConfig.h:41,
from Marlin\src\HAL\HAL_STM32F1\u8g_com_stm32duino_fsmc.cpp:29:
Marlin\src\HAL\HAL_STM32F1\../../inc/SanityCheck.h:957:8: error: #error "SERVO0_PIN must be defined for your servo or BLTOUCH probe."
#error "SERVO0_PIN must be defined for your servo or BLTOUCH probe."
^~~~~
Marlin\src\HAL\HAL_STM32F1\../../inc/SanityCheck.h:1777:4: error: #error "TMC2208 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
#error "TMC2208 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
^~~~~
Marlin\src\HAL\HAL_STM32F1\../../inc/SanityCheck.h:1841:4: error: #error "TMC2208 Software Serial is supported only on AVR and LPC1768 platforms."
#error "TMC2208 Software Serial is supported only on AVR and LPC1768 platforms."
^~~~~
Marlin\src\HAL\HAL_STM32F1\HAL_Servo_STM32F1.cpp: In member function 'bool libServo::attach(int32_t, int32_t, int32_t)':
Marlin\src\HAL\HAL_STM32F1\HAL_Servo_STM32F1.cpp:77:11: warning: unused variable 'tchan' [-Wunused-variable]
uint8_t tchan = PIN_MAP[this->pin].timer_channel;
^~~~~
In file included from Marlin\src\HAL\HAL_STM32F1\../../inc/MarlinConfig.h:41,
from Marlin\src\HAL\HAL_STM32F1\watchdog_STM32F1.cpp:29:
Marlin\src\HAL\HAL_STM32F1\../../inc/SanityCheck.h:957:8: error: #error "SERVO0_PIN must be defined for your servo or BLTOUCH probe."
#error "SERVO0_PIN must be defined for your servo or BLTOUCH probe."
^~~~~
In file included from Marlin\src\HAL\HAL_STM32F1\../../inc/MarlinConfig.h:30,
from Marlin\src\HAL\HAL_STM32F1\HAL_Servo_STM32F1.cpp:26:
Marlin\src\HAL\HAL_STM32F1\../../inc/../HAL/HAL_STM32F1/HAL.h: At global scope:
Marlin\src\HAL\HAL_STM32F1\../../inc/../HAL/HAL_STM32F1/HAL.h:183:12: warning: 'int freeMemory()' defined but not used [-Wunused-function]
static int freeMemory() {
^~~~~~~~~~
Marlin\src\HAL\HAL_STM32F1\../../inc/SanityCheck.h:1777:4: error: #error "TMC2208 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
#error "TMC2208 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
^~~~~
Marlin\src\HAL\HAL_STM32F1\../../inc/SanityCheck.h:1841:4: error: #error "TMC2208 Software Serial is supported only on AVR and LPC1768 platforms."
#error "TMC2208 Software Serial is supported only on AVR and LPC1768 platforms."
^~~~~
In file included from Marlin\src\HAL\shared\backtrace\../../../inc/MarlinConfigPre.h:36,
from Marlin\src\HAL\shared\backtrace\../../../inc/MarlinConfig.h:28,
from Marlin\src\HAL\shared\backtrace\unwmemaccess.cpp:18:
Marlin\src\HAL\shared\backtrace\../../../inc/Conditionals_LCD.h:51: warning: "ENCODER_PULSES_PER_STEP" redefined
#define ENCODER_PULSES_PER_STEP 1

In file included from Marlin\src\HAL\shared\backtrace\../../../inc/MarlinConfigPre.h:35,
from Marlin\src\HAL\shared\backtrace\../../../inc/MarlinConfig.h:28,
from Marlin\src\HAL\shared\backtrace\unwmemaccess.cpp:18:
Marlin\src\HAL\shared\backtrace\../../../inc/../../Configuration.h:1547: note: this is the location of the previous definition
#define ENCODER_PULSES_PER_STEP 2

In file included from Marlin\src\HAL\shared\backtrace\../../../inc/MarlinConfigPre.h:36,
from Marlin\src\HAL\shared\backtrace\../../../inc/MarlinConfig.h:28,
from Marlin\src\HAL\shared\backtrace\unwmemaccess.cpp:18:
Marlin\src\HAL\shared\backtrace\../../../inc/Conditionals_LCD.h:52: warning: "ENCODER_STEPS_PER_MENU_ITEM" redefined
#define ENCODER_STEPS_PER_MENU_ITEM 1

In file included from Marlin\src\HAL\shared\backtrace\../../../inc/MarlinConfigPre.h:35,
from Marlin\src\HAL\shared\backtrace\../../../inc/MarlinConfig.h:28,
from Marlin\src\HAL\shared\backtrace\unwmemaccess.cpp:18:
Marlin\src\HAL\shared\backtrace\../../../inc/../../Configuration.h:1553: note: this is the location of the previous definition
#define ENCODER_STEPS_PER_MENU_ITEM 2

In file included from Marlin\src\HAL\shared\../../inc/MarlinConfig.h:41,
from Marlin\src\HAL\shared\I2cEeprom.cpp:28:
Marlin\src\HAL\shared\../../inc/SanityCheck.h:957:8: error: #error "SERVO0_PIN must be defined for your servo or BLTOUCH probe."
#error "SERVO0_PIN must be defined for your servo or BLTOUCH probe."
^~~~~
Marlin\src\HAL\shared\../../inc/SanityCheck.h:1777:4: error: #error "TMC2208 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
#error "TMC2208 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."Compiling .pioenvs\BIGTREE_SKR_MINI\src\src\Marlin.cpp.o

^~~~~
Marlin\src\HAL\shared\../../inc/SanityCheck.h:1841:4: error: #error "TMC2208 Software Serial is supported only on AVR and LPC1768 platforms."
#error "TMC2208 Software Serial is supported only on AVR and LPC1768 platforms."
^~~~~
In file included from Marlin\src\HAL\HAL_STM32F1\../../inc/MarlinConfig.h:30,
from Marlin\src\HAL\HAL_STM32F1\persistent_store_flash.cpp:32:
Marlin\src\HAL\HAL_STM32F1\../../inc/../HAL/HAL_STM32F1/HAL.h:183:12: warning: 'int freeMemory()' defined but not used [-Wunused-function]
static int freeMemory() {
^~~~~~~~~~
In file included from Marlin\src\HAL\shared\../../inc/MarlinConfig.h:41,
from Marlin\src\HAL\shared\SpiEeprom.cpp:28:
Marlin\src\HAL\shared\../../inc/SanityCheck.h:957:8: error: #error "SERVO0_PIN must be defined for your servo or BLTOUCH probe."
#error "SERVO0_PIN must be defined for your servo or BLTOUCH probe."
^~~~~
Marlin\src\HAL\shared\../../inc/SanityCheck.h:1777:4: error: #error "TMC2208 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
#error "TMC2208 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
^~~~~
Marlin\src\HAL\shared\../../inc/SanityCheck.h:1841:4: error: #error "TMC2208 Software Serial is supported only on AVR and LPC1768 platforms."
#error "TMC2208 Software Serial is supported only on AVR and LPC1768 platforms."
^~~~~
In file included from Marlin\src\HAL\shared\../../inc/MarlinConfigPre.h:36,
from Marlin\src\HAL\shared\../../inc/MarlinConfig.h:28,
from Marlin\src\HAL\shared\servo.cpp:54:
Marlin\src\HAL\shared\../../inc/Conditionals_LCD.h:51: warning: "ENCODER_PULSES_PER_STEP" redefined
#define ENCODER_PULSES_PER_STEP 1

In file included from Marlin\src\HAL\shared\../../inc/MarlinConfigPre.h:35,
from Marlin\src\HAL\shared\../../inc/MarlinConfig.h:28,
from Marlin\src\HAL\shared\servo.cpp:54:
Marlin\src\HAL\shared\../../inc/../../Configuration.h:1547: note: this is the location of the previous definition
#define ENCODER_PULSES_PER_STEP 2

In file included from Marlin\src\HAL\shared\../../inc/MarlinConfigPre.h:36,
from Marlin\src\HAL\shared\../../inc/MarlinConfig.h:28,
from Marlin\src\HAL\shared\servo.cpp:54:
Compiling .pioenvs\BIGTREE_SKR_MINI\src\src\core\serial.cpp.oMarlin\src\HAL\shared\../../inc/Conditionals_LCD.h:52: warning: "ENCODER_STEPS_PER_MENU_ITEM" redefined

#define ENCODER_STEPS_PER_MENU_ITEM 1

In file included from Marlin\src\HAL\shared\../../inc/MarlinConfigPre.h:35,
from Marlin\src\HAL\shared\../../inc/MarlinConfig.h:28,
from Marlin\src\HAL\shared\servo.cpp:54:
Marlin\src\HAL\shared\../../inc/../../Configuration.h:1553: note: this is the location of the previous definition
#define ENCODER_STEPS_PER_MENU_ITEM 2

Marlin\src\HAL\HAL_STM32F1\persistent_store_sdcard.cpp: In static member function 'static bool PersistentStore::write_data(int&, const uint8_t*, size_t, uint16_t*)':
Marlin\src\HAL\HAL_STM32F1\persistent_store_sdcard.cpp:65:21: warning: comparison of integer expressions of different signedness: 'int' and 'const size_t' {aka 'const unsigned int'} [-Wsign-compare]
for (int i = 0; i < size; i++)
~~^~~~~~
Marlin\src\HAL\HAL_STM32F1\persistent_store_sdcard.cpp: In static member function 'static bool PersistentStore::read_data(int&, uint8_t*, size_t, uint16_t*, bool)':
Marlin\src\HAL\HAL_STM32F1\persistent_store_sdcard.cpp:73:21: warning: comparison of integer expressions of different signedness: 'int' and 'const size_t' {aka 'const unsigned int'} [-Wsign-compare]
for (int i = 0; i < size; i++) {
~~^~~~~~
In file included from Marlin\src\HAL\HAL_STM32F1\../../inc/MarlinConfig.h:30,
from Marlin\src\HAL\HAL_STM32F1\persistent_store_sdcard.cpp:30:
Marlin\src\HAL\HAL_STM32F1\../../inc/../HAL/HAL_STM32F1/HAL.h: At global scope:
Marlin\src\HAL\HAL_STM32F1\../../inc/../HAL/HAL_STM32F1/HAL.h:183:12: warning: 'int freeMemory()' defined but not used [-Wunused-function]
static int freeMemory() {
^~~~~~~~~~
In file included from Marlin\src\HAL\HAL_STM32F1\../../inc/MarlinConfig.h:30,C
ompiling .pioenvs\BIGTREE_SKR_MINI\src\src\core\utility.cpp.ofrom Marlin\src\HAL\HAL_STM32F1\u8g_com_stm32duino_fsmc.cpp:29:

Marlin\src\HAL\HAL_STM32F1\../../inc/../HAL/HAL_STM32F1/HAL.h:183:12: warning: 'int freeMemory()' defined but not used [-Wunused-function]
static int freeMemory() {
^~~~~~~~~~
In file included from Marlin\src\HAL\HAL_STM32F1\../../inc/MarlinConfig.h:30,
from Marlin\src\HAL\HAL_STM32F1\watchdog_STM32F1.cpp:29:
Marlin\src\HAL\HAL_STM32F1\../../inc/../HAL/HAL_STM32F1/HAL.h:183:12: warning: 'int freeMemory()' defined but not used [-Wunused-function]
static int freeMemory() {
^~~~~~~~~~
*** [.pioenvs\BIGTREE_SKR_MINI\src\src\HAL\HAL_STM32F1\HAL_Servo_STM32F1.cpp.o] Error 1
*** [.pioenvs\BIGTREE_SKR_MINI\src\src\HAL\HAL_STM32F1\persistent_store_flash.cpp.o] Error 1
*** [.pioenvs\BIGTREE_SKR_MINI\src\src\HAL\HAL_STM32F1\persistent_store_sdcard.cpp.o] Error 1
*** [.pioenvs\BIGTREE_SKR_MINI\src\src\HAL\HAL_STM32F1\u8g_com_stm32duino_fsmc.cpp.o] Error 1
*** [.pioenvs\BIGTREE_SKR_MINI\src\src\HAL\HAL_STM32F1\watchdog_STM32F1.cpp.o] Error 1
In file included from Marlin\src\HAL\shared\../../inc/MarlinConfig.h:30,
from Marlin\src\HAL\shared\I2cEeprom.cpp:28:
Marlin\src\HAL\shared\../../inc/../HAL/HAL_STM32F1/HAL.h:183:12: warning: 'int freeMemory()' defined but not used [-Wunused-function]
static int freeMemory() {
^~~~~~~~~~
In file included from Marlin\src\HAL\shared\../../inc/MarlinConfig.h:30,
from Marlin\src\HAL\shared\SpiEeprom.cpp:28:
Marlin\src\HAL\shared\../../inc/../HAL/HAL_STM32F1/HAL.h:183:12: warning: 'int freeMemory()' defined but not used [-Wunused-function]
static int freeMemory() {
^~~~~~~~~~
In file included from Marlin\src\HAL\shared\backtrace\../../../inc/MarlinConfig.h:41,
from Marlin\src\HAL\shared\backtrace\unwmemaccess.cpp:18:
Marlin\src\HAL\shared\backtrace\../../../inc/SanityCheck.h:957:8: error: #error "SERVO0_PIN must be defined for your servo or BLTOUCH probe."
#error "SERVO0_PIN must be defined for your servo or BLTOUCH probe."
^~~~~
Marlin\src\HAL\shared\backtrace\../../../inc/SanityCheck.h:1777:4: error: #error "TMC2208 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
#error "TMC2208 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
^~~~~
Marlin\src\HAL\shared\backtrace\../../../inc/SanityCheck.h:1841:4: error: #error "TMC2208 Software Serial is supported only on AVR and LPC1768 platforms."
#error "TMC2208 Software Serial is supported only on AVR and LPC1768 platforms."
^~~~~
*** [.pioenvs\BIGTREE_SKR_MINI\src\src\HAL\shared\I2cEeprom.cpp.o] Error 1
*** [.pioenvs\BIGTREE_SKR_MINI\src\src\HAL\shared\SpiEeprom.cpp.o] Error 1
In file included from Marlin\src\HAL\shared\../../inc/MarlinConfig.h:41,
from Marlin\src\HAL\shared\servo.cpp:54:
Marlin\src\HAL\shared\../../inc/SanityCheck.h:957:8: error: #error "SERVO0_PIN must be defined for your servo or BLTOUCH probe."
#error "SERVO0_PIN must be defined for your servo or BLTOUCH probe."
^~~~~
Marlin\src\HAL\shared\../../inc/SanityCheck.h:1777:4: error: #error "TMC2208 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
#error "TMC2208 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
^~~~~
In file included from Marlin\src\inc/MarlinConfigPre.h:36,
from Marlin\src\inc/MarlinConfig.h:28,
from Marlin\src\Marlin.h:24,
from Marlin\src\Marlin.cpp:31:
Marlin\src\inc/Conditionals_LCD.h:51: warning: "ENCODER_PULSES_PER_STEP" redefined
#define ENCODER_PULSES_PER_STEP 1

Marlin\src\HAL\shared\../../inc/SanityCheck.h:1841:4: error: #error "TMC2208 Software Serial is supported only on AVR and LPC1768 platforms."
#error "TMC2208 Software Serial is supported only on AVR and LPC1768 platforms."
^~~~~
In file included from Marlin\src\inc/MarlinConfigPre.h:35,
from Marlin\src\inc/MarlinConfig.h:28,
from Marlin\src\Marlin.h:24,
from Marlin\src\Marlin.cpp:31:
Marlin\src\inc/../../Configuration.h:1547: note: this is the location of the previous definition
#define ENCODER_PULSES_PER_STEP 2

In file included from Marlin\src\inc/MarlinConfigPre.h:36,
from Marlin\src\inc/MarlinConfig.h:28,
from Marlin\src\Marlin.h:24,
from Marlin\src\Marlin.cpp:31:
Marlin\src\inc/Conditionals_LCD.h:52: warning: "ENCODER_STEPS_PER_MENU_ITEM" redefined
#define ENCODER_STEPS_PER_MENU_ITEM 1

In file included from Marlin\src\inc/MarlinConfigPre.h:35,
from Marlin\src\inc/MarlinConfig.h:28,
from Marlin\src\Marlin.h:24,
from Marlin\src\Marlin.cpp:31:
Marlin\src\inc/../../Configuration.h:1553: note: this is the location of the previous definition
#define ENCODER_STEPS_PER_MENU_ITEM 2

In file included from Marlin\src\core\../inc/MarlinConfigPre.h:36,
from Marlin\src\core\serial.h:24,
from Marlin\src\core\serial.cpp:23:
Marlin\src\core\../inc/Conditionals_LCD.h:51: warning: "ENCODER_PULSES_PER_STEP" redefined
#define ENCODER_PULSES_PER_STEP 1

In file included from Marlin\src\core\../inc/MarlinConfigPre.h:35,
from Marlin\src\core\serial.h:24,
from Marlin\src\core\serial.cpp:23:
Marlin\src\core\../inc/../../Configuration.h:1547: note: this is the location of the previous definition
#define ENCODER_PULSES_PER_STEP 2

In file included from Marlin\src\core\../inc/MarlinConfigPre.h:36,
from Marlin\src\core\serial.h:24,
from Marlin\src\core\serial.cpp:23:
Marlin\src\core\../inc/Conditionals_LCD.h:52: warning: "ENCODER_STEPS_PER_MENU_ITEM" redefined
#define ENCODER_STEPS_PER_MENU_ITEM 1

In file included from Marlin\src\core\../inc/MarlinConfigPre.h:35,
from Marlin\src\core\serial.h:24,
from Marlin\src\core\serial.cpp:23:
Marlin\src\core\../inc/../../Configuration.h:1553: note: this is the location of the previous definition
#define ENCODER_STEPS_PER_MENU_ITEM 2

In file included from Marlin\src\HAL\shared\backtrace\../../../inc/MarlinConfig.h:30,
from Marlin\src\HAL\shared\backtrace\unwmemaccess.cpp:18:
Marlin\src\HAL\shared\backtrace\../../../inc/../HAL/HAL_STM32F1/HAL.h:183:12: warning: 'int freeMemory()' defined but not used [-Wunused-function]
static int freeMemory() {
^~~~~~~~~~
In file included from Marlin\src\core\../inc/MarlinConfigPre.h:36,
from Marlin\src\core\utility.h:24,
from Marlin\src\core\utility.cpp:23:
Marlin\src\core\../inc/Conditionals_LCD.h:51: warning: "ENCODER_PULSES_PER_STEP" redefined
#define ENCODER_PULSES_PER_STEP 1

In file included from Marlin\src\core\../inc/MarlinConfigPre.h:35,
from Marlin\src\core\utility.h:24,
from Marlin\src\core\utility.cpp:23:
Marlin\src\core\../inc/../../Configuration.h:1547: note: this is the location of the previous definition
#define ENCODER_PULSES_PER_STEP 2

In file included from Marlin\src\core\../inc/MarlinConfigPre.h:36,
from Marlin\src\core\utility.h:24,
from Marlin\src\core\utility.cpp:23:
Marlin\src\core\../inc/Conditionals_LCD.h:52: warning: "ENCODER_STEPS_PER_MENU_ITEM" redefined
#define ENCODER_STEPS_PER_MENU_ITEM 1

In file included from Marlin\src\core\../inc/MarlinConfigPre.h:35,
from Marlin\src\core\utility.h:24,
from Marlin\src\core\utility.cpp:23:
Marlin\src\core\../inc/../../Configuration.h:1553: note: this is the location of the previous definition
#define ENCODER_STEPS_PER_MENU_ITEM 2

*** [.pioenvs\BIGTREE_SKR_MINI\src\src\HAL\shared\backtrace\unwmemaccess.cpp.o] Error 1
In file included from Marlin\src\HAL\shared\../../inc/MarlinConfig.h:30,
from Marlin\src\HAL\shared\servo.cpp:54:
Marlin\src\HAL\shared\../../inc/../HAL/HAL_STM32F1/HAL.h:183:12: warning: 'int freeMemory()' defined but not used [-Wunused-function]
static int freeMemory() {
^~~~~~~~~~
*** [.pioenvs\BIGTREE_SKR_MINI\src\src\HAL\shared\servo.cpp.o] Error 1
In file included from Marlin\src\inc/MarlinConfig.h:41,
from Marlin\src\Marlin.h:24,
from Marlin\src\Marlin.cpp:31:
Marlin\src\inc/SanityCheck.h:957:8: error: #error "SERVO0_PIN must be defined for your servo or BLTOUCH probe."
#error "SERVO0_PIN must be defined for your servo or BLTOUCH probe."
^~~~~
Marlin\src\inc/SanityCheck.h:1777:4: error: #error "TMC2208 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
#error "TMC2208 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
^~~~~
Marlin\src\inc/SanityCheck.h:1841:4: error: #error "TMC2208 Software Serial is supported only on AVR and LPC1768 platforms."
#error "TMC2208 Software Serial is supported only on AVR and LPC1768 platforms."
^~~~~
In file included from Marlin\src\core\../inc/MarlinConfig.h:41,
from Marlin\src\core\language.h:24,
from Marlin\src\core\serial.cpp:24:
Marlin\src\core\../inc/SanityCheck.h:957:8: error: #error "SERVO0_PIN must be defined for your servo or BLTOUCH probe."
#error "SERVO0_PIN must be defined for your servo or BLTOUCH probe."
^~~~~
Marlin\src\core\../inc/SanityCheck.h:1777:4: error: #error "TMC2208 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
#error "TMC2208 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
^~~~~
Marlin\src\core\../inc/SanityCheck.h:1841:4: error: #error "TMC2208 Software Serial is supported only on AVR and LPC1768 platforms."
#error "TMC2208 Software Serial is supported only on AVR and LPC1768 platforms."
^~~~~
In file included from Marlin\src\core\../inc/MarlinConfig.h:41,
from Marlin\src\core\../Marlin.h:24,
from Marlin\src\core\utility.cpp:25:
Marlin\src\core\../inc/SanityCheck.h:957:8: error: #error "SERVO0_PIN must be defined for your servo or BLTOUCH probe."
#error "SERVO0_PIN must be defined for your servo or BLTOUCH probe."
^~~~~
Marlin\src\core\../inc/SanityCheck.h:1777:4: error: #error "TMC2208 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
#error "TMC2208 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
^~~~~
Marlin\src\core\../inc/SanityCheck.h:1841:4: error: #error "TMC2208 Software Serial is supported only on AVR and LPC1768 platforms."
#error "TMC2208 Software Serial is supported only on AVR and LPC1768 platforms."
^~~~~
In file included from Marlin\src\core\serial.h:25,
from Marlin\src\core\serial.cpp:23:
Marlin\src\core\../HAL/HAL_STM32F1/HAL.h:183:12: warning: 'int freeMemory()' defined but not used [-Wunused-function]
static int freeMemory() {
^~~~~~~~~~
*** [.pioenvs\BIGTREE_SKR_MINI\src\src\core\serial.cpp.o] Error 1
In file included from Marlin\src\core\../inc/MarlinConfig.h:30,
from Marlin\src\core\../Marlin.h:24,
from Marlin\src\core\utility.cpp:25:
Marlin\src\core\../inc/../HAL/HAL_STM32F1/HAL.h:183:12: warning: 'int freeMemory()' defined but not used [-Wunused-function]
static int freeMemory() {
^~~~~~~~~~
In file included from .piolibdeps\TMCStepper_ID5513\src/TMCStepper.h:12,
from Marlin\src\module/stepper_indirection.h:59,
from Marlin\src\module/stepper.h:232,
from Marlin\src\Marlin.cpp:36:
C:\users\anm8t\.platformio\packages\framework-arduinoststm32\STM32F1\libraries\SPI\src/SPI.h:164:13: warning: unnecessary parentheses in declaration of '_spi1_this' [-Wparentheses]
static void (*_spi1_this);
^
C:\users\anm8t\.platformio\packages\framework-arduinoststm32\STM32F1\libraries\SPI\src/SPI.h:165:13: warning: unnecessary parentheses in declaration of '_spi2_this' [-Wparentheses]
static void (*_spi2_this);
^
C:\users\anm8t\.platformio\packages\framework-arduinoststm32\STM32F1\libraries\SPI\src/SPI.h:167:13: warning: unnecessary parentheses in declaration of '_spi3_this' [-Wparentheses]
static void (*_spi3_this);
^
C:\users\anm8t\.platformio\packages\framework-arduinoststm32\STM32F1\libraries\SPI\src/SPI.h:167:15: warning: '_spi3_this' defined but not used [-Wunused-variable]
static void (*_spi3_this);
^~~~~~~~~~
C:\users\anm8t\.platformio\packages\framework-arduinoststm32\STM32F1\libraries\SPI\src/SPI.h:165:15: warning: '_spi2_this' defined but not used [-Wunused-variable]
static void (*_spi2_this);
^~~~~~~~~~
C:\users\anm8t\.platformio\packages\framework-arduinoststm32\STM32F1\libraries\SPI\src/SPI.h:164:15: warning: '_spi1_this' defined but not used [-Wunused-variable]
static void (*_spi1_this);
^~~~~~~~~~
C:\users\anm8t\.platformio\packages\framework-arduinoststm32\STM32F1\libraries\SPI\src/SPI.h:163:16: warning: 'ff' defined but not used [-Wunused-variable]
static uint8_t ff = 0XFF;
^~
*** [.pioenvs\BIGTREE_SKR_MINI\src\src\Marlin.cpp.o] Error 1
*** [.pioenvs\BIGTREE_SKR_MINI\src\src\core\utility.cpp.o] Error 1

![PIO_problems](https://user-images.githubusercontent.com/30998739/58926040-b7410500-8717-11e9-8eb4-a9b3475fc7a0.JPG)

**Comment by anm8tor** [comment]
Ignore the BLTOUCH errors, I was able to get those resolved by adding "#define SERVO0_PIN     PA2" to the pins_BIGTREE_SKR_MINI_V1.1.h file

**Comment by rhialto56** [comment]
You must define all pins in your pin_board.h

**Comment by anm8tor** [comment]
Yes,  I understand. Are you able to provide any help on which pins are defined as what?  



Sent from Yahoo Mail on Android 
 
  On Sun, Jun 9, 2019 at 2:10 AM, rhialto56<notifications@github.com> wrote:   
You must define all pins in your pin_board.h
